version: "3.7"
services:
    fulltext-search:
        image: zinkl/fulltext-search
        ports:
            - "8421:8421"
        environment:
            INDEX_STORAGE_POLICY: ${INDEX_STORAGE_POLICY}
    p2pframework:
        image: zinkl/p2p-dht
        ports:
            - "8070:8070"
            - "8090:8090"
        environment:
            PEER_LIST: ${PEER_LIST}
            PEER_IP: "0.0.0.0"
        volumes: 
            - "~/p2p/data:/tmp/datastore"
    userinterface:
        image: zinkl/p2p-userinterface
        ports:
            - "8080:3000"
        environment:
            MongoConnectionString: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${DATA_HOST}:8430"
    