version: "3.7"
services:
    userinterface:
        image: zinkl/p2p-userinterface
        ports:
            - "8080:3000"
        depends_on: 
            - fulltext-search
    fulltext-search:
        image: zinkl/fulltext-search
        expose:
            - "8421"
    p2pframework:
        image: zinkl/p2p-dht
        expose:
            - "8090"
    